### ISSUE TITLE
make遇错

### ISSUE THREAD

**Issue by luckypoem** [messyidea/qtunnel-libev#1]
hi.

yudeMacBook-Air:qtunnel-c brite$ make
gcc -g -w qtunnel.c qtunnel.h -o qtunnel-c -lcrypto -lpthread -lev
clang: error: cannot specify -o when generating multiple output files
make: *** [qtunnel-c] Error 1
yudeMacBook-Air:qtunnel-c brite$

怎么解决？

**Comment by messyidea** [comment]
手头没有mac的编译环境，linux试了下，发现clang编译的时候要把`qtunnel.h`给去掉。
即:
```
clang -g -w qtunnel.c -o qtunnel-c -lcrypto -lpthread -lev
```
这样就没有问题了。
当然linux编译的时候要先装上`libssl-dev`和`libev-dev`，mac的话可能这两者要下源代码编译了，会麻烦一点

**Comment by luckypoem** [comment]
还是不行：
yudeMacBook-Air:qtunnel-libev brite$ clang -g -w qtunnel.c -o qtunnel-c -lcrypto -lpthread -lev
qtunnel.c:11:10: fatal error: 'openssl/rc4.h' file not found
#include <openssl/rc4.h>
         ^~~~~~~~~~~~~~~
1 error generated.
yudeMacBook-Air:qtunnel-libev brite$

**Comment by messyidea** [comment]
这个是因为项目依赖openssl,linux需要安装libssl-dev,mac的话可能要下载openssl源码编译。
mac的话还是用原版go写的[qtunnel](https://github.com/getqujing/qtunnel)吧，毕竟golang编译起来比较方便。
